version: '2'
services:
    web:
        build: .
        command: python3 runserver.py
        volumes:
            - .:/usr/src/app
        ports:
            - "8888:8888"
        depends_on:
            - db
    db:
        image: mysql
        volumes:
            - .:/usr/src/db
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: "octopuslabs"
          MYSQL_ROOT_PASSWORD: "password"